---
collections:
  - name: ansible.utils
    version: 2.5.2
  - name: ansible.posix
    version: 1.3.0
  - name: community.docker
    version: 2.3.0
  - name: community.general
    version: 4.6.1
  - name: kubernetes.core
    version: 2.3.0
  - name: community.sops
    version: 1.2.1
roles:
  - src: geerlingguy.pip
    version: 2.1.0
  - src: geerlingguy.docker
    version: 4.2.0
  - src: xanmanning.k3s
    version: v3.1.1
  - src: https://github.com/mrlesmithjr/ansible-netplan.git
    scm: git
    version: v0.3.0
