---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: benji-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/elemental-lf/benji
  ref:
    tag: v0.17.0
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
