---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s#server-control-plane-configuration

# Define the host as control plane nodes
k3s_control_node: true

# k3s settings for all control-plane nodes
k3s_server:
  datastore-endpoint: postgres://cluster:{{ SECRET_POSTGRES_PASSWORD }}@{{ SECRET_POSTGRES_HOST }}:{{ SECRET_POSTGRES_HOSTPORT }}/cluster?sslmode=disable
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ kubevip_address }}"
    # haproxy
    - "{{ k3s_registration_address }}"
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  #flannel-iface: "eth0"
  disable:
    - flannel
    - traefik
    - servicelb
    - metrics-server
    - local-storage
  disable-network-policy: true
  disable-cloud-controller: false
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  cluster-cidr: "10.69.0.0/16"
  # Network CIDR to use for service IPs
  service-cidr: "10.96.0.0/16"
  # Required to monitor component with kube-prometheus-stack
  etcd-expose-metrics: true
  kubelet-arg:
    - "feature-gates=EphemeralContainers=true,MixedProtocolLBService=true,ReadWriteOncePod=true,GracefulNodeShutdown=true"
    - "node-status-update-frequency=4s"
  # Required to use monitor these components with kube-prometheus-stack
  kube-controller-manager-arg:
    - "feature-gates=EphemeralContainers=true,MixedProtocolLBService=true,ReadWriteOncePod=true"
    - "bind-address=0.0.0.0"
    - "node-monitor-period=4s"
    - "node-monitor-grace-period=16s"
    - "pod-eviction-timeout=20s"
  kube-proxy-arg:
    - "feature-gates=EphemeralContainers=true,MixedProtocolLBService=true,ReadWriteOncePod=true"
    - "metrics-bind-address=0.0.0.0"
  kube-scheduler-arg:
    - "feature-gates=EphemeralContainers=true,MixedProtocolLBService=true,ReadWriteOncePod=true"
    - "bind-address=0.0.0.0"
  # anonymous-auth=true Required for HAProxy health-checks
  kube-apiserver-arg:
    - "feature-gates=EphemeralContainers=true,MixedProtocolLBService=true,ReadWriteOncePod=true"
    - "anonymous-auth=true"
    - "oidc-issuer-url=https://dex.k8s.aml.ink/"
    - "oidc-client-id=dex-k8s-authenticator"
    - "oidc-username-claim=preferred_username"
    - "oidc-groups-claim=groups"
    # Allow pods to be rescheduled quicker in the case of a node failure
    # https://github.com/k3s-io/k3s/issues/1264
    - "default-not-ready-toleration-seconds=20"
    - "default-unreachable-toleration-seconds=20"
  node-label:
    - "master=yes"
  node-taint:
    #- "k3s-controlplane=true:NoSchedule"
    - "CriticalAddonsOnly=true:NoSchedule"

